CREATE DATABASE URBAN_HOTEL;
USE URBAN_HOTEL;

-- CREATING TABLES

-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (CUSTOMER_ID INT PRIMARY KEY, NAME VARCHAR(100), CONTACT_INFO VARCHAR(15), EMAIL VARCHAR(100));

-- TABLES TABLE
CREATE TABLE DINING_TABLES (TABLE_ID INT PRIMARY KEY, CAPACITY INT, LOCATION VARCHAR(100));

-- RSERVATIONS TABLE
CREATE TABLE RESERVATIONS (RESERVATION_ID INT PRIMARY KEY, CUSTOMER_ID INT, TABLE_ID INT, RESERVATION_DATE DATE, TIM_E TIME, GUESTS_COUNT INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID), 
FOREIGN KEY (TABLE_ID) REFERENCES DINING_TABLES(TABLE_ID));  

-- DINING HISTORY TABLE
CREATE TABLE DINING_HISTORY (DINING_ID INT PRIMARY KEY, CUSTOMER_ID INT, RESERVATION_ID INT, TOTAL_BILL DECIMAL(10,2), PAYMENT_METHOD VARCHAR(50),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(RESERVATION_ID));  


-- INSERTING TABLES

-- INSERTING DATA INTO CUSTOMERS
INSERT INTO CUSTOMERS()VALUES(101,"KAILASH","9840015692","KAILASH123@GMAIL.COM"),(102,"RAMEN","5624897123","RAMEN456@GMAIL.COM"),(103,"SUDHA","8547618523","SUDHA@GMAIL.COM"),
(104,"DAVID","7845962451","DAVID12@GMAIL.COM");

-- INSERTING DATA INTO TABLES
INSERT INTO DINING_TABLES()VALUES(001, 4, "WINDOW SEAT"),(002, 2, "NEAR ENTERANCE"),(003, 6, "PRIVATE ROOM"),(004, 5, "VIP TABLE");

-- INSERTING DATA INTO RESERVATIONS
INSERT INTO RESERVATIONS()VALUES(201, 101, 001, "2024-11-05", "7:15", 4),(202, 102, 002, "2024-11-10", "8:20", 6),(203, 103, 003, "2024-11-15", "9:45", 2),
(204, 103, 004, "2024-11-20", "10:20", 3);  

-- INSERTING DATA INTO HISTORY 
INSERT INTO DINING_HISTORY() VALUES (01, 101, 201, 700, "CARD"),(02, 102, 202, 585, "CASH"),(03, 103, 203, 900, "CARD"),(04, 104, 204, 789, "CASH");


-- QUERIES

-- LISTING THE CUSTOMERS TABLE
SELECT*FROM CUSTOMERS;

-- LISTING THE DINING TABLE
SELECT*FROM DINING_TABLES;

-- LISTING THE RESERVATION TABLE
SELECT*FROM RESERVATIONS;

-- LISTING THE DATA INTO HISTORY
SELECT*FROM DINING_HISTORY;

-- FIND RESERVATIONS FOR A SPECIFIC DATE
SELECT*FROM RESERVATIONS WHERE RESERVATION_DATE ="2024-11-15";

-- LIST ALL RESERVATIONS FOR A SPECIFIC CUSTOMER "NAME = RAMEN"
SELECT*FROM RESERVATIONS JOIN CUSTOMERS ON RESERVATIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
WHERE CUSTOMERS.NAME = "RAMEN";

-- CALCULATE TOTAL SPENDING OF EACH CUSTOMERS
SELECT CUSTOMERS.NAME, SUM(DINING_HISTORY.TOTAL_BILL) AS TOTAL_SPENT FROM CUSTOMERS
JOIN DINING_HISTORY ON CUSTOMERS.CUSTOMER_ID = DINING_HISTORY.CUSTOMER_ID GROUP BY CUSTOMERS.NAME; 

-- SHOW RESERVATIONS WITH TABLE DETAILS
SELECT*FROM RESERVATIONS JOIN CUSTOMERS ON RESERVATIONS.CUSTOMER_ID - CUSTOMERS.CUSTOMER_ID
JOIN DINING_TABLES ON RESERVATIONS.TABLE_ID = DINING_TABLES.TABLE_ID;

-- LIST TABLES WITH THE LOW CAPACITY
SELECT*FROM DINING_TABLES WHERE CAPACITY<5;

-- LIST CUSTOMERS WITH RESERVATIONS ON A SPECIFIC DATE
SELECT CUSTOMERS.NAME, RESERVATIONS.RESERVATION_DATE, RESERVATIONS.TIM_E FROM RESERVATIONS
JOIN CUSTOMERS ON RESERVATIONS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID WHERE RESERVATIONS.RESERVATION_DATE = "2024-11-05";

